name: PHP CS Fixer

on:
  push:
    branches: [ tests, main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-php-8.4-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-php-8.4-

      - name: Installer les dépendances
        env:
          APP_ENV: test
          DEFAULT_URI: "http://localhost"
        run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

      - name: Lancer PHP CS Fixer en vérification
        run: vendor/bin/php-cs-fixer fix

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none
      - run: composer install --no-interaction --prefer-dist --no-progress
      - run: php bin/console cache:warmup --env=dev
      - run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G

  phpunit:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      APP_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/app_test?serverVersion=16&charset=utf8"

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none
      - run: composer install --no-interaction --prefer-dist --no-progress
      - name: Exécuter la migration sur la base de CI
        run: php bin/console doctrine:migrations:migrate --no-interaction
      - name: Lancer la suite de tests
        run: vendor/bin/phpunit
